#!/bin/sh

print_wifi() {
    iwconfig wlp3s0 |\
        awk -F '"|level=|\n' \
        '/Signal|ESSID/ {print $2}' |\
        awk 'BEGIN {RS=""}{gsub(/\n/," ",$0); \
        printf "%s %d %s", $1, $2, $3}'
}

print_ip() {
    ip route |\
        awk 'BEGIN {RS=""}{gsub(/\n/,"",$0); \
        print $3}'
}


print_net() {
    ip=$(print_ip)
    wifi=$(print_wifi)

    if [ -z $ip ]
    then
        printf 'disconnected'
    elif [ -z $wifi ]
    then
        printf '%s' "$ip"
    else
        printf '%s | %s' "$ip" "$wifi"
        
    fi
}

print_mem() {
    awk '/Mem/{print$2}' /proc/meminfo |\
    awk 'BEGIN {RS = "";FS = "\n"} ;\
        {printf("%d/%d mB\n", ($1-$3)/1024, ($1-$2)/1000)}'
}

print_temp() {
    head -c 2 /sys/class/thermal/thermal_zone0/temp
}

print_vol() {
    amixer -M get Master |\
        awk -F"[][]" '/Mono.+/ {print $6=="off" ?\
        "muted": "vol "$2}'
}

print_bat() {
    status=$(cat /sys/class/power_supply/BAT0/status)
    level=$(cat /sys/class/power_supply/BAT0/capacity)
    if [ $status = "Charging" ]
    then
        printf 'char %d%%' "$level"
    else
        printf 'bat %d%%' "$level"
    fi
}

print_date() {
    date +'%a %d %b | %l:%M %P'
} 


printf '%s | %s | %dC | %s | %s | %s\n' "$(print_net)" "$(print_mem)" "$(print_temp)" "$(print_vol)" "$(print_bat)" "$(print_date)"
