#!/bin/sh -e

#eval $(ssh-agent)

export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=sway
export _JAVA_AWT_WM_NONREPARENTING=1
export MOZ_ENABLE_WAYLAND=1

if [ -z "$XDG_RUNTIME_DIR" ]; then
	export XDG_RUNTIME_DIR=/tmp
fi

case "$1" in
debug)
	~/src/sway/build/sway/sway -d >/tmp/sway.log 2>&1
	;;
"")
	sway >/tmp/sway.log 2>&1
	;;
*)
	echo >&2 "Invalid argument: $1"
	exit 1
esac
